---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 'A través de un idioma que tanto ella como las personas podamos entender:  los
    lenguajes de programación.'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 'A través de un idioma que tanto ella como las personas podamos entender:  inglés.'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A través de cálculos matemáticos.
  checked: false
name: "¿Programar? ... ¡Sí! ... ¡Programar!"
